# A. Purpose of experiment

Manual **Run All** xLSTM depth study replacing the scientific role of the legacy BiGRU depth study. Only the MagNet representation-pretraining stage is executable now. The test split is never accessed. The downstream confirmation remains blocked until real fine-tuning data are available.

**Saved-output notice:** Existing outputs in this file predate the v1.1 migration and are retained only as historical execution evidence. Run All replaces them with current v1.1 validation output.

In [5]:
from pathlib import Path
PROJECT_ROOT = Path.cwd().resolve()
RUN_DEPTHS = [2, 4, 6, 8, 10]
FORCE_RETRAIN = False
AUTO_RESUME = True
print('PASS — manual controls loaded')
print(f'RUN_DEPTHS={RUN_DEPTHS}')
print(f'FORCE_RETRAIN={FORCE_RETRAIN} (applies only to depths explicitly listed in RUN_DEPTHS)')
print(f'AUTO_RESUME={AUTO_RESUME}')
output_root = PROJECT_ROOT / 'experiments/xlstm_depth_v1'
has_results = output_root.exists() and any(output_root.rglob('training_summary.json'))
print(f"DEPTH EXPERIMENT STATUS: {'RECOVERY/COMPLETED ARTIFACTS FOUND' if has_results else 'NEW RUN'}")

PASS — manual controls loaded
RUN_DEPTHS=[2, 4, 6, 8, 10]
FORCE_RETRAIN=False (applies only to depths explicitly listed in RUN_DEPTHS)
AUTO_RESUME=True
DEPTH EXPERIMENT STATUS: NEW RUN

# B. Environment verification

In [6]:
import sys
import os
import numpy as np
import torch
REQUIRED_INTERPRETER = os.environ.get('MEPI_REQUIRED_INTERPRETER')
gpu_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'UNAVAILABLE'
print(f'sys.executable: {sys.executable}')
print(f'Python version: {sys.version.replace(chr(10), chr(32))}')
print(f'PyTorch version: {torch.__version__}')
print(f'CUDA build: {torch.version.cuda}')
print(f'CUDA available: {torch.cuda.is_available()}')
print(f'GPU name: {gpu_name}')
print(f'NumPy version: {np.__version__}')
if REQUIRED_INTERPRETER and str(Path(sys.executable).resolve()) != str(Path(REQUIRED_INTERPRETER).resolve()):
    print('FAIL — wrong interpreter')
    raise RuntimeError('Select Python (trans-core), restart the kernel, then Run All')
if not torch.cuda.is_available():
    print('FAIL — CUDA is required for the scientific run')
    raise RuntimeError('CUDA is unavailable in Python (trans-core); stop before training')
print('PASS — required Python (trans-core) interpreter and CUDA are active')

sys.executable: <USER_HOME>/miniconda3/envs/trans-core/bin/python
Python version: 3.11.15 | packaged by conda-forge | (main, Aug 11 2026, 10:26:29) [GCC 14.4.0]
PyTorch version: 2.5.1
CUDA build: 12.1
CUDA available: True
GPU name: NVIDIA GeForce RTX 3050
NumPy version: 2.4.6
PASS — required Python (trans-core) interpreter and CUDA are active

In [7]:
from pathlib import Path
import sys

# Locate MEPI project root robustly whether the notebook is launched
# from the repository root or from notebooks/.
cwd = Path.cwd().resolve()

candidates = [cwd, *cwd.parents]
PROJECT_ROOT = next(
    (p for p in candidates if (p / "src" / "mepi_v1").is_dir()),
    None,
)

if PROJECT_ROOT is None:
    raise RuntimeError(
        f"Could not locate MEPI project root from working directory: {cwd}"
    )

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Working directory :", cwd)
print("PROJECT_ROOT      :", PROJECT_ROOT)
print("Python path entry :", sys.path[0])

assert (PROJECT_ROOT / "src" / "mepi_v1").is_dir()
print("[PASS] MEPI project source path configured")

Working directory : <REPOSITORY_ROOT>/notebooks
PROJECT_ROOT      : <REPOSITORY_ROOT>
Python path entry : <REPOSITORY_ROOT>
[PASS] MEPI project source path configured

# C. Frozen-protocol verification

In [8]:
from src.mepi_v1.reproducibility import sha256_file
EXPECTED_PROTOCOL_SHA256 = 'a515052cd2f8cf2970b731cfb48dee055c316a5d4acc0f0ca90313436c344c0f'
protocol_paths = [PROJECT_ROOT / 'MEPI-FROZEN-PROTOCOL v1.1.md', PROJECT_ROOT / 'docs/MEPI-FROZEN-PROTOCOL v1.1.md']
protocol_hashes = [sha256_file(path) for path in protocol_paths]
passed = protocol_hashes == [EXPECTED_PROTOCOL_SHA256, EXPECTED_PROTOCOL_SHA256]
print(f"{'PASS' if passed else 'FAIL'} — frozen protocol hashes: {protocol_hashes}")
if not passed:
    raise RuntimeError('Frozen protocol is missing or changed; training is blocked')

PASS — frozen protocol hashes: ['ef8f1f85c94ddc18645d25f4537a3eed45e8f46c6d900f419ff3c8f36be99cef', 'ef8f1f85c94ddc18645d25f4537a3eed45e8f46c6d900f419ff3c8f36be99cef']

# D. Dataset and split verification

In [9]:
from src.mepi_v1.xlstm_depth import XLSTMDepthRun
probe = XLSTMDepthRun(PROJECT_ROOT, 2)
dataset_check = probe.validate_dataset()
assert dataset_check['waveform_shape'][1] == 1024
assert dataset_check['test_split_accessed'] is False
print('PASS — B(t) has 1024 points; only train and validation manifests were inspected')

[PASS] Depth-study dataset: <REPOSITORY_ROOT>/data/raw/source_datasets/Dataset/magnet_pretrain_186k.h5
[PASS] Train/validation counts: {'train': 149405, 'validation': 18676}
[PASS] Test manifest and test dataset not opened
PASS — B(t) has 1024 points; only train and validation manifests were inspected

# E. Dataset and split fingerprints

In [10]:
EXPECTED_DATASET_SHA256 = '0aca43184e9bd6cc90eec736a89fe1ea32f45b126527cb97918cd92684ac2c19'
EXPECTED_TRAIN_SHA256 = '2e06050bbe1cff8b6f4f7ae3a99788d6914e214353a5e6a2f2ece7463b6377b0'
EXPECTED_VALIDATION_SHA256 = 'aa7d1ee30ca3f3967eadee81d2a31e0a9bcb7e0bc5421f36cb849d6da1dc9749'
prepared = probe._prepare()
actual = {
    'dataset': prepared['compatibility']['dataset_fingerprint'],
    'train': sha256_file(prepared['manifests']['train']),
    'validation': sha256_file(prepared['manifests']['validation']),
}
expected = {'dataset': EXPECTED_DATASET_SHA256, 'train': EXPECTED_TRAIN_SHA256, 'validation': EXPECTED_VALIDATION_SHA256}
print(f"{'PASS' if actual == expected else 'FAIL'} — fingerprints: {actual}")
if actual != expected:
    raise RuntimeError('Frozen dataset or train/validation manifests changed')
print('PASS — MagNet test manifest was not read or fingerprinted')

PASS — fingerprints: {'dataset': '0aca43184e9bd6cc90eec736a89fe1ea32f45b126527cb97918cd92684ac2c19', 'train': '2e06050bbe1cff8b6f4f7ae3a99788d6914e214353a5e6a2f2ece7463b6377b0', 'validation': 'aa7d1ee30ca3f3967eadee81d2a31e0a9bcb7e0bc5421f36cb849d6da1dc9749'}
PASS — MagNet test manifest was not read or fingerprinted

# F. xLSTM baseline architecture

In [11]:
from src.mepi_v1.backbones import XLSTMBackbone
from src.mepi_v1.models import PretrainingModel
baseline = PretrainingModel('xLSTM', material_count=10, latent_dim=256, backbone_layers=2)
assert isinstance(baseline.backbone, XLSTMBackbone)
print('PASS — waveform encoder -> operating encoder -> fusion -> stacked xLSTM blocks -> temporary material-routed heads')
print('PASS — material identity is not a predictive input; PIRL and MTPH are absent')

PASS — waveform encoder -> operating encoder -> fusion -> stacked xLSTM blocks -> temporary material-routed heads
PASS — material identity is not a predictive input; PIRL and MTPH are absent

# G. Controlled variables

In [12]:
fixed = {
 'waveform_length': 1024, 'predictive_tabular': ['frequency', 'temperature'],
 'latent_dim': 256, 'epochs': 10, 'batch_size': probe.config['training']['batch_size'],
 'optimizer': 'AdamW', 'learning_rate': probe.config['training']['learning_rate'],
 'scheduler': 'constant LambdaLR', 'dataloader': {k: probe.config['training'].get(k) for k in ['num_workers','pin_memory','persistent_workers','prefetch_factor','cache_mode']},
 'amp': probe.config['training']['amp'], 'tf32': probe.config['runtime']['allow_tf32'],
 'seed': probe.seed, 'target_transform': prepared['preprocessing']['target'],
}
print('PASS — depth is the only varied model/configuration value')
fixed

PASS — depth is the only varied model/configuration value

{'waveform_length': 1024,
 'predictive_tabular': ['frequency', 'temperature'],
 'latent_dim': 256,
 'epochs': 10,
 'batch_size': 256,
 'optimizer': 'AdamW',
 'learning_rate': 3e-05,
 'scheduler': 'constant LambdaLR',
 'dataloader': {'num_workers': 4,
  'pin_memory': True,
  'persistent_workers': True,
  'prefetch_factor': 2,
  'cache_mode': 'hdf5'},
 'amp': True,
 'tf32': True,
 'seed': 42,
 'target_transform': {'transform': 'log1p_standardize',
  'scaler': 'population mean and standard deviation',
  'inverse': 'expm1(z * scale + mean)',
  'state': {'mean': [11.073220047200586],
   'scale': [1.849061097213353],
   'fitted_split': 'train',
   'sample_count': 149405}}}

# H. Depth candidates [2, 4, 6, 8, 10]

In [13]:
from src.mepi_v1.xlstm_depth import DEPTHS
invalid = sorted(set(RUN_DEPTHS) - set(DEPTHS))
print(f"{'PASS' if not invalid else 'FAIL'} — canonical DEPTHS={list(DEPTHS)}; requested RUN_DEPTHS={RUN_DEPTHS}")
if invalid:
    raise ValueError(f'Unsupported depth values: {invalid}')

PASS — canonical DEPTHS=[2, 4, 6, 8, 10]; requested RUN_DEPTHS=[2, 4, 6, 8, 10]

# I. Parameter-count preview

In [14]:
import pandas as pd
preview = []
for depth in DEPTHS:
    model = PretrainingModel('xLSTM', material_count=10, latent_dim=256, backbone_layers=depth)
    preview.append({'depth': depth, 'parameter_count': sum(p.numel() for p in model.parameters()), 'block_count': len(model.backbone.blocks)})
preview_df = pd.DataFrame(preview)
assert preview_df['parameter_count'].is_monotonic_increasing
print('PASS — block count equals depth and parameter count increases with depth')
preview_df

PASS — block count equals depth and parameter count increases with depth

   depth  parameter_count  block_count
0      2          2019338            2
1      4          3336202            4
2      6          4653066            6
3      8          5969930            8
4     10          7286794           10

# J. Training setup

Each candidate has its own visible cell below. Compatible completed candidates are skipped; interrupted candidates resume automatically from `last_checkpoint.pt`.

In [15]:
import torch
from src.mepi_v1.xlstm_depth import official_pretraining_snapshot
official_before = official_pretraining_snapshot(PROJECT_ROOT)
depth_results = {}
def run_manual_depth(depth):
    if depth not in RUN_DEPTHS:
        print(f'Depth {depth}/10: SKIPPED BY RUN_DEPTHS')
        return None
    run = XLSTMDepthRun(PROJECT_ROOT, depth, force_retrain=FORCE_RETRAIN, auto_resume=AUTO_RESUME)
    status = run.inspect_status()
    if status['status'] == 'COMPLETE':
        summary = run.validate_completed_compatibility()
        print(f'Depth {depth}/10: COMPLETE — skipped safely')
        depth_results[depth] = summary
        return summary
    print(f"Depth {depth}/10: {'RESUME' if status['status'] == 'INCOMPLETE' else 'FROM SCRATCH'}")
    run.check_environment(require_cuda=True)
    run.validate_source_protocol()
    run.validate_dataset()
    run.construct_model_smoke()
    run.inspect_checkpoint()
    torch.cuda.reset_peak_memory_stats()
    run.train_or_resume()
    summary = run.finalize_validation_only(peak_gpu_memory_bytes=int(torch.cuda.max_memory_allocated()))
    run.write_depth_evidence(summary, official_before)
    if official_pretraining_snapshot(PROJECT_ROOT) != official_before:
        raise RuntimeError('Official pretraining evidence changed during the depth run')
    print(f"PASS — Depth {depth} complete; validation MAE_norm={summary['validation_metrics']['normalized_mae']}")
    print(f"Checkpoint saved: {summary['best_checkpoint']}")
    depth_results[depth] = summary
    return summary
print('PASS — manual training helper ready; no candidate has been launched by this setup cell')

PASS — manual training helper ready; no candidate has been launched by this setup cell

# K. Depth-2 training

In [16]:
depth_2_summary = run_manual_depth(2)

STATUS: NEW RUN
Depth 2/10: FROM SCRATCH
[PASS] Project root: <REPOSITORY_ROOT>
[PASS] Python executable: <USER_HOME>/miniconda3/envs/trans-core/bin/python
[PASS] Python version: 3.11.15 | packaged by conda-forge | (main, Aug 11 2026, 10:26:29) [GCC 14.4.0]
[PASS] PyTorch import: 2.5.1
[PASS] PyTorch CUDA version: 12.1
[PASS] CUDA available: True
[PASS] GPU model: NVIDIA GeForce RTX 3050
[PASS] Python (trans-core) kernel interpreter: display='Python (trans-core)'; kernel=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11; active=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11
[PASS] Frozen protocol found: <REPOSITORY_ROOT>/docs/MEPI_FROZEN_PROTOCOL_v1.0.md
[PASS] src.mepi_v1 imports: source fingerprint 14bc064a53f22849c3723254a57d6604a3b14339bf987c22d2821cffeefd3816
[PASS] All eight candidate configs share one non-architecture setup: 05e4f2864bbbcaf68de732438a869f75bab0273e646166a669686f3694ab67a1
Git SHA: UNAVAILABLE (source-tree fingerprint retained)
[PASS] Depth-study dataset: <REPOSITORY_ROOT>/data/raw/source_datasets/Dataset/magnet_pretrain_186k.h5
[PASS] Train/validation counts: {'train': 149405, 'validation': 18676}
[PASS] Test manifest and test dataset not opened
{
  "model": "xLSTM",
  "parameter_count": 2019338,
  "waveform_input_shape": [
    1,
    1,
    1024
  ],
  "tabular_input_shape": [
    1,
    2
  ],
  "target_shape": [
    1
  ],
  "output_shape": [
    1
  ],
  "temporary_heads": 10
}
Material ID used as predictive input: NO
Material metadata routes only the temporary regression head: YES
PIRL instantiated: NO
MTPH instantiated: NO
[PASS] No recovery checkpoint: a new run will initialize from scratch
STATUS: NEW RUN
TRAINING MODE: FROM SCRATCH
Depth 2 | Epoch 1/10
train loss: 0.245498
validation MAE_norm: 0.123385
validation RMSE: 0.166795
validation R2: 0.972677
lr: 3e-05
elapsed: 100.4s
GPU allocated: 1.65 GiB
Epoch 2/10 | step 1000 | train loss 0.059199 | lr 3e-05 | elapsed 161.1s | GPU memory 1.65 GiB
Depth 2 | Epoch 2/10
train loss: 0.055704
validation MAE_norm: 0.086735
validation RMSE: 0.120917
validation R2: 0.985640
lr: 3e-05
elapsed: 194.9s
GPU allocated: 1.65 GiB
Depth 2 | Epoch 3/10
train loss: 0.036061
validation MAE_norm: 0.072119
validation RMSE: 0.101944
validation R2: 0.989793
lr: 3e-05
elapsed: 292.0s
GPU allocated: 1.65 GiB
Epoch 4/10 | step 2000 | train loss 0.029928 | lr 3e-05 | elapsed 329.6s | GPU memory 1.65 GiB
Depth 2 | Epoch 4/10
train loss: 0.028117
validation MAE_norm: 0.055471
validation RMSE: 0.077356
validation R2: 0.994123
lr: 3e-05
elapsed: 389.2s
GPU allocated: 1.65 GiB
Depth 2 | Epoch 5/10
train loss: 0.024146
validation MAE_norm: 0.057277
validation RMSE: 0.077650
validation R2: 0.994078
lr: 3e-05
elapsed: 487.6s
GPU allocated: 1.65 GiB
Epoch 6/10 | step 3000 | train loss 0.021268 | lr 3e-05 | elapsed 499.9s | GPU memory 1.65 GiB
Depth 2 | Epoch 6/10
train loss: 0.020733
validation MAE_norm: 0.044475
validation RMSE: 0.066572
validation R2: 0.995647
lr: 3e-05
elapsed: 583.3s
GPU allocated: 1.65 GiB
Epoch 7/10 | step 4000 | train loss 0.018630 | lr 3e-05 | elapsed 656.9s | GPU memory 1.65 GiB
Depth 2 | Epoch 7/10
train loss: 0.018470
validation MAE_norm: 0.046196
validation RMSE: 0.068833
validation R2: 0.995347
lr: 3e-05
elapsed: 682.3s
GPU allocated: 1.65 GiB
Depth 2 | Epoch 8/10
train loss: 0.016485
validation MAE_norm: 0.037961
validation RMSE: 0.053906
validation R2: 0.997146
lr: 3e-05
elapsed: 787.1s
GPU allocated: 1.65 GiB
Epoch 9/10 | step 5000 | train loss 0.014956 | lr 3e-05 | elapsed 837.0s | GPU memory 1.65 GiB
Depth 2 | Epoch 9/10
train loss: 0.014694
validation MAE_norm: 0.034605
validation RMSE: 0.049907
validation R2: 0.997554
lr: 3e-05
elapsed: 884.1s
GPU allocated: 1.65 GiB
Depth 2 | Epoch 10/10
train loss: 0.013420
validation MAE_norm: 0.036497
validation RMSE: 0.048172
validation R2: 0.997721
lr: 3e-05
elapsed: 978.7s
GPU allocated: 1.65 GiB
PASS — Depth 2 complete; validation MAE_norm=0.034604851700193597
Checkpoint saved: <REPOSITORY_ROOT>/experiments/xlstm_depth_v1/depth_2/best_checkpoint.pt

# L. Depth-4 training

In [17]:
depth_4_summary = run_manual_depth(4)

STATUS: NEW RUN
Depth 4/10: FROM SCRATCH
[PASS] Project root: <REPOSITORY_ROOT>
[PASS] Python executable: <USER_HOME>/miniconda3/envs/trans-core/bin/python
[PASS] Python version: 3.11.15 | packaged by conda-forge | (main, Aug 11 2026, 10:26:29) [GCC 14.4.0]
[PASS] PyTorch import: 2.5.1
[PASS] PyTorch CUDA version: 12.1
[PASS] CUDA available: True
[PASS] GPU model: NVIDIA GeForce RTX 3050
[PASS] Python (trans-core) kernel interpreter: display='Python (trans-core)'; kernel=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11; active=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11
[PASS] Frozen protocol found: <REPOSITORY_ROOT>/docs/MEPI_FROZEN_PROTOCOL_v1.0.md
[PASS] src.mepi_v1 imports: source fingerprint 14bc064a53f22849c3723254a57d6604a3b14339bf987c22d2821cffeefd3816
[PASS] All eight candidate configs share one non-architecture setup: 05e4f2864bbbcaf68de732438a869f75bab0273e646166a669686f3694ab67a1
Git SHA: UNAVAILABLE (source-tree fingerprint retained)
[PASS] Depth-study dataset: <REPOSITORY_ROOT>/data/raw/source_datasets/Dataset/magnet_pretrain_186k.h5
[PASS] Train/validation counts: {'train': 149405, 'validation': 18676}
[PASS] Test manifest and test dataset not opened
{
  "model": "xLSTM",
  "parameter_count": 3336202,
  "waveform_input_shape": [
    1,
    1,
    1024
  ],
  "tabular_input_shape": [
    1,
    2
  ],
  "target_shape": [
    1
  ],
  "output_shape": [
    1
  ],
  "temporary_heads": 10
}
Material ID used as predictive input: NO
Material metadata routes only the temporary regression head: YES
PIRL instantiated: NO
MTPH instantiated: NO
[PASS] No recovery checkpoint: a new run will initialize from scratch
STATUS: NEW RUN
TRAINING MODE: FROM SCRATCH
Depth 4 | Epoch 1/10
train loss: 0.222594
validation MAE_norm: 0.135928
validation RMSE: 0.193154
validation R2: 0.963358
lr: 3e-05
elapsed: 140.5s
GPU allocated: 2.49 GiB
Epoch 2/10 | step 1000 | train loss 0.055189 | lr 3e-05 | elapsed 233.6s | GPU memory 2.49 GiB
Depth 4 | Epoch 2/10
train loss: 0.050359
validation MAE_norm: 0.078726
validation RMSE: 0.112391
validation R2: 0.987594
lr: 3e-05
elapsed: 280.6s
GPU allocated: 2.49 GiB
Depth 4 | Epoch 3/10
train loss: 0.030253
validation MAE_norm: 0.059431
validation RMSE: 0.083405
validation R2: 0.993168
lr: 3e-05
elapsed: 419.4s
GPU allocated: 2.49 GiB
Epoch 4/10 | step 2000 | train loss 0.024839 | lr 3e-05 | elapsed 474.7s | GPU memory 2.49 GiB
Depth 4 | Epoch 4/10
train loss: 0.023036
validation MAE_norm: 0.046810
validation RMSE: 0.066790
validation R2: 0.995619
lr: 3e-05
elapsed: 558.7s
GPU allocated: 2.49 GiB
Depth 4 | Epoch 5/10
train loss: 0.018700
validation MAE_norm: 0.047227
validation RMSE: 0.065383
validation R2: 0.995801
lr: 3e-05
elapsed: 697.8s
GPU allocated: 2.49 GiB
Epoch 6/10 | step 3000 | train loss 0.017580 | lr 3e-05 | elapsed 716.2s | GPU memory 2.49 GiB
Depth 4 | Epoch 6/10
train loss: 0.015824
validation MAE_norm: 0.039435
validation RMSE: 0.055228
validation R2: 0.997004
lr: 3e-05
elapsed: 836.5s
GPU allocated: 2.49 GiB
Epoch 7/10 | step 4000 | train loss 0.014611 | lr 3e-05 | elapsed 945.9s | GPU memory 2.49 GiB
Depth 4 | Epoch 7/10
train loss: 0.014373
validation MAE_norm: 0.036405
validation RMSE: 0.051507
validation R2: 0.997394
lr: 3e-05
elapsed: 975.1s
GPU allocated: 2.49 GiB
Depth 4 | Epoch 8/10
train loss: 0.013177
validation MAE_norm: 0.032874
validation RMSE: 0.046163
validation R2: 0.997907
lr: 3e-05
elapsed: 1113.4s
GPU allocated: 2.49 GiB
Epoch 9/10 | step 5000 | train loss 0.012069 | lr 3e-05 | elapsed 1185.5s | GPU memory 2.49 GiB
Depth 4 | Epoch 9/10
train loss: 0.011429
validation MAE_norm: 0.026314
validation RMSE: 0.037244
validation R2: 0.998638
lr: 3e-05
elapsed: 1251.1s
GPU allocated: 2.49 GiB
Depth 4 | Epoch 10/10
train loss: 0.010452
validation MAE_norm: 0.029365
validation RMSE: 0.039502
validation R2: 0.998468
lr: 3e-05
elapsed: 1389.5s
GPU allocated: 2.49 GiB
PASS — Depth 4 complete; validation MAE_norm=0.026313903800429913
Checkpoint saved: <REPOSITORY_ROOT>/experiments/xlstm_depth_v1/depth_4/best_checkpoint.pt

# M. Depth-6 training

In [18]:
depth_6_summary = run_manual_depth(6)

STATUS: NEW RUN
Depth 6/10: FROM SCRATCH
[PASS] Project root: <REPOSITORY_ROOT>
[PASS] Python executable: <USER_HOME>/miniconda3/envs/trans-core/bin/python
[PASS] Python version: 3.11.15 | packaged by conda-forge | (main, Aug 11 2026, 10:26:29) [GCC 14.4.0]
[PASS] PyTorch import: 2.5.1
[PASS] PyTorch CUDA version: 12.1
[PASS] CUDA available: True
[PASS] GPU model: NVIDIA GeForce RTX 3050
[PASS] Python (trans-core) kernel interpreter: display='Python (trans-core)'; kernel=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11; active=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11
[PASS] Frozen protocol found: <REPOSITORY_ROOT>/docs/MEPI_FROZEN_PROTOCOL_v1.0.md
[PASS] src.mepi_v1 imports: source fingerprint 14bc064a53f22849c3723254a57d6604a3b14339bf987c22d2821cffeefd3816
[PASS] All eight candidate configs share one non-architecture setup: 05e4f2864bbbcaf68de732438a869f75bab0273e646166a669686f3694ab67a1
Git SHA: UNAVAILABLE (source-tree fingerprint retained)
[PASS] Depth-study dataset: <REPOSITORY_ROOT>/data/raw/source_datasets/Dataset/magnet_pretrain_186k.h5
[PASS] Train/validation counts: {'train': 149405, 'validation': 18676}
[PASS] Test manifest and test dataset not opened
{
  "model": "xLSTM",
  "parameter_count": 4653066,
  "waveform_input_shape": [
    1,
    1,
    1024
  ],
  "tabular_input_shape": [
    1,
    2
  ],
  "target_shape": [
    1
  ],
  "output_shape": [
    1
  ],
  "temporary_heads": 10
}
Material ID used as predictive input: NO
Material metadata routes only the temporary regression head: YES
PIRL instantiated: NO
MTPH instantiated: NO
[PASS] No recovery checkpoint: a new run will initialize from scratch
STATUS: NEW RUN
TRAINING MODE: FROM SCRATCH
Depth 6 | Epoch 1/10
train loss: 0.218918
validation MAE_norm: 0.117726
validation RMSE: 0.172637
validation R2: 0.970729
lr: 3e-05
elapsed: 186.1s
GPU allocated: 3.32 GiB
Epoch 2/10 | step 1000 | train loss 0.046388 | lr 3e-05 | elapsed 310.3s | GPU memory 3.32 GiB
Depth 6 | Epoch 2/10
train loss: 0.042631
validation MAE_norm: 0.082599
validation RMSE: 0.111036
validation R2: 0.987891
lr: 3e-05
elapsed: 372.3s
GPU allocated: 3.32 GiB
Depth 6 | Epoch 3/10
train loss: 0.027729
validation MAE_norm: 0.060886
validation RMSE: 0.080947
validation R2: 0.993565
lr: 3e-05
elapsed: 558.5s
GPU allocated: 3.32 GiB
Epoch 4/10 | step 2000 | train loss 0.023380 | lr 3e-05 | elapsed 633.0s | GPU memory 3.32 GiB
Depth 6 | Epoch 4/10
train loss: 0.022418
validation MAE_norm: 0.052982
validation RMSE: 0.075541
validation R2: 0.994396
lr: 3e-05
elapsed: 744.9s
GPU allocated: 3.32 GiB
Depth 6 | Epoch 5/10
train loss: 0.019864
validation MAE_norm: 0.042505
validation RMSE: 0.058384
validation R2: 0.996652
lr: 3e-05
elapsed: 931.8s
GPU allocated: 3.32 GiB
Epoch 6/10 | step 3000 | train loss 0.017909 | lr 3e-05 | elapsed 956.4s | GPU memory 3.32 GiB
Depth 6 | Epoch 6/10
train loss: 0.017284
validation MAE_norm: 0.042461
validation RMSE: 0.058265
validation R2: 0.996666
lr: 3e-05
elapsed: 1118.5s
GPU allocated: 3.32 GiB
Epoch 7/10 | step 4000 | train loss 0.015881 | lr 3e-05 | elapsed 1266.6s | GPU memory 3.32 GiB
Depth 6 | Epoch 7/10
train loss: 0.015736
validation MAE_norm: 0.042437
validation RMSE: 0.055540
validation R2: 0.996970
lr: 3e-05
elapsed: 1304.9s
GPU allocated: 3.32 GiB
Depth 6 | Epoch 8/10
train loss: 0.013126
validation MAE_norm: 0.036470
validation RMSE: 0.048673
validation R2: 0.997673
lr: 3e-05
elapsed: 1491.6s
GPU allocated: 3.32 GiB
Epoch 9/10 | step 5000 | train loss 0.011584 | lr 3e-05 | elapsed 1589.6s | GPU memory 3.32 GiB
Depth 6 | Epoch 9/10
train loss: 0.011284
validation MAE_norm: 0.028942
validation RMSE: 0.038288
validation R2: 0.998560
lr: 3e-05
elapsed: 1680.7s
GPU allocated: 3.32 GiB
Depth 6 | Epoch 10/10
train loss: 0.009925
validation MAE_norm: 0.028504
validation RMSE: 0.037054
validation R2: 0.998652
lr: 3e-05
elapsed: 1869.4s
GPU allocated: 3.32 GiB
PASS — Depth 6 complete; validation MAE_norm=0.028503619574478573
Checkpoint saved: <REPOSITORY_ROOT>/experiments/xlstm_depth_v1/depth_6/best_checkpoint.pt

# N. Depth-8 training

In [19]:
depth_8_summary = run_manual_depth(8)

STATUS: NEW RUN
Depth 8/10: FROM SCRATCH
[PASS] Project root: <REPOSITORY_ROOT>
[PASS] Python executable: <USER_HOME>/miniconda3/envs/trans-core/bin/python
[PASS] Python version: 3.11.15 | packaged by conda-forge | (main, Aug 11 2026, 10:26:29) [GCC 14.4.0]
[PASS] PyTorch import: 2.5.1
[PASS] PyTorch CUDA version: 12.1
[PASS] CUDA available: True
[PASS] GPU model: NVIDIA GeForce RTX 3050
[PASS] Python (trans-core) kernel interpreter: display='Python (trans-core)'; kernel=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11; active=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11
[PASS] Frozen protocol found: <REPOSITORY_ROOT>/docs/MEPI_FROZEN_PROTOCOL_v1.0.md
[PASS] src.mepi_v1 imports: source fingerprint 14bc064a53f22849c3723254a57d6604a3b14339bf987c22d2821cffeefd3816
[PASS] All eight candidate configs share one non-architecture setup: 05e4f2864bbbcaf68de732438a869f75bab0273e646166a669686f3694ab67a1
Git SHA: UNAVAILABLE (source-tree fingerprint retained)
[PASS] Depth-study dataset: <REPOSITORY_ROOT>/data/raw/source_datasets/Dataset/magnet_pretrain_186k.h5
[PASS] Train/validation counts: {'train': 149405, 'validation': 18676}
[PASS] Test manifest and test dataset not opened
{
  "model": "xLSTM",
  "parameter_count": 5969930,
  "waveform_input_shape": [
    1,
    1,
    1024
  ],
  "tabular_input_shape": [
    1,
    2
  ],
  "target_shape": [
    1
  ],
  "output_shape": [
    1
  ],
  "temporary_heads": 10
}
Material ID used as predictive input: NO
Material metadata routes only the temporary regression head: YES
PIRL instantiated: NO
MTPH instantiated: NO
[PASS] No recovery checkpoint: a new run will initialize from scratch
STATUS: NEW RUN
TRAINING MODE: FROM SCRATCH
Depth 8 | Epoch 1/10
train loss: 0.216914
validation MAE_norm: 0.112332
validation RMSE: 0.166735
validation R2: 0.972696
lr: 3e-05
elapsed: 239.3s
GPU allocated: 4.15 GiB
Epoch 2/10 | step 1000 | train loss 0.044877 | lr 3e-05 | elapsed 397.9s | GPU memory 4.15 GiB
Depth 8 | Epoch 2/10
train loss: 0.041538
validation MAE_norm: 0.070866
validation RMSE: 0.093730
validation R2: 0.991372
lr: 3e-05
elapsed: 477.1s
GPU allocated: 4.15 GiB
Depth 8 | Epoch 3/10
train loss: 0.027384
validation MAE_norm: 0.073012
validation RMSE: 0.095947
validation R2: 0.990959
lr: 3e-05
elapsed: 714.9s
GPU allocated: 4.15 GiB
Epoch 4/10 | step 2000 | train loss 0.024360 | lr 3e-05 | elapsed 809.6s | GPU memory 4.15 GiB
Depth 8 | Epoch 4/10
train loss: 0.023045
validation MAE_norm: 0.059800
validation RMSE: 0.081846
validation R2: 0.993421
lr: 3e-05
elapsed: 952.3s
GPU allocated: 4.15 GiB
Depth 8 | Epoch 5/10
train loss: 0.018851
validation MAE_norm: 0.041572
validation RMSE: 0.056059
validation R2: 0.996913
lr: 3e-05
elapsed: 1190.3s
GPU allocated: 4.15 GiB
Epoch 6/10 | step 3000 | train loss 0.015956 | lr 3e-05 | elapsed 1221.6s | GPU memory 4.15 GiB
Depth 8 | Epoch 6/10
train loss: 0.015128
validation MAE_norm: 0.040270
validation RMSE: 0.050909
validation R2: 0.997455
lr: 3e-05
elapsed: 1428.8s
GPU allocated: 4.15 GiB
Epoch 7/10 | step 4000 | train loss 0.012504 | lr 3e-05 | elapsed 1617.4s | GPU memory 4.15 GiB
Depth 8 | Epoch 7/10
train loss: 0.012350
validation MAE_norm: 0.036927
validation RMSE: 0.050056
validation R2: 0.997539
lr: 3e-05
elapsed: 1666.2s
GPU allocated: 4.15 GiB
Depth 8 | Epoch 8/10
train loss: 0.011689
validation MAE_norm: 0.026880
validation RMSE: 0.036873
validation R2: 0.998665
lr: 3e-05
elapsed: 1904.7s
GPU allocated: 4.15 GiB
Epoch 9/10 | step 5000 | train loss 0.010641 | lr 3e-05 | elapsed 2029.9s | GPU memory 4.15 GiB
Depth 8 | Epoch 9/10
train loss: 0.010352
validation MAE_norm: 0.022691
validation RMSE: 0.030936
validation R2: 0.999060
lr: 3e-05
elapsed: 2142.9s
GPU allocated: 4.15 GiB
Depth 8 | Epoch 10/10
train loss: 0.009030
validation MAE_norm: 0.020495
validation RMSE: 0.027949
validation R2: 0.999233
lr: 3e-05
elapsed: 2381.5s
GPU allocated: 4.15 GiB
PASS — Depth 8 complete; validation MAE_norm=0.020495040982892985
Checkpoint saved: <REPOSITORY_ROOT>/experiments/xlstm_depth_v1/depth_8/best_checkpoint.pt

# O. Depth-10 training

In [20]:
depth_10_summary = run_manual_depth(10)

STATUS: NEW RUN
Depth 10/10: FROM SCRATCH
[PASS] Project root: <REPOSITORY_ROOT>
[PASS] Python executable: <USER_HOME>/miniconda3/envs/trans-core/bin/python
[PASS] Python version: 3.11.15 | packaged by conda-forge | (main, Aug 11 2026, 10:26:29) [GCC 14.4.0]
[PASS] PyTorch import: 2.5.1
[PASS] PyTorch CUDA version: 12.1
[PASS] CUDA available: True
[PASS] GPU model: NVIDIA GeForce RTX 3050
[PASS] Python (trans-core) kernel interpreter: display='Python (trans-core)'; kernel=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11; active=<USER_HOME>/miniconda3/envs/trans-core/bin/python3.11
[PASS] Frozen protocol found: <REPOSITORY_ROOT>/docs/MEPI_FROZEN_PROTOCOL_v1.0.md
[PASS] src.mepi_v1 imports: source fingerprint 14bc064a53f22849c3723254a57d6604a3b14339bf987c22d2821cffeefd3816
[PASS] All eight candidate configs share one non-architecture setup: 05e4f2864bbbcaf68de732438a869f75bab0273e646166a669686f3694ab67a1
Git SHA: UNAVAILABLE (source-tree fingerprint retained)
[PASS] Depth-study dataset: <REPOSITORY_ROOT>/data/raw/source_datasets/Dataset/magnet_pretrain_186k.h5
[PASS] Train/validation counts: {'train': 149405, 'validation': 18676}
[PASS] Test manifest and test dataset not opened
{
  "model": "xLSTM",
  "parameter_count": 7286794,
  "waveform_input_shape": [
    1,
    1,
    1024
  ],
  "tabular_input_shape": [
    1,
    2
  ],
  "target_shape": [
    1
  ],
  "output_shape": [
    1
  ],
  "temporary_heads": 10
}
Material ID used as predictive input: NO
Material metadata routes only the temporary regression head: YES
PIRL instantiated: NO
MTPH instantiated: NO
[PASS] No recovery checkpoint: a new run will initialize from scratch
STATUS: NEW RUN
TRAINING MODE: FROM SCRATCH
Depth 10 | Epoch 1/10
train loss: 0.212150
validation MAE_norm: 0.126090
validation RMSE: 0.175783
validation R2: 0.969652
lr: 3e-05
elapsed: 287.7s
GPU allocated: 4.99 GiB
Epoch 2/10 | step 1000 | train loss 0.053859 | lr 3e-05 | elapsed 479.7s | GPU memory 4.99 GiB
Depth 10 | Epoch 2/10
train loss: 0.048980
validation MAE_norm: 0.082004
validation RMSE: 0.117945
validation R2: 0.986338
lr: 3e-05
elapsed: 575.8s
GPU allocated: 4.99 GiB
Depth 10 | Epoch 3/10
train loss: 0.030616
validation MAE_norm: 0.075597
validation RMSE: 0.097434
validation R2: 0.990676
lr: 3e-05
elapsed: 872.6s
GPU allocated: 4.99 GiB
Epoch 4/10 | step 2000 | train loss 0.025125 | lr 3e-05 | elapsed 991.7s | GPU memory 4.99 GiB
Depth 10 | Epoch 4/10
train loss: 0.023505
validation MAE_norm: 0.058605
validation RMSE: 0.075443
validation R2: 0.994410
lr: 3e-05
elapsed: 1171.5s
GPU allocated: 4.99 GiB
Depth 10 | Epoch 5/10
train loss: 0.018398
validation MAE_norm: 0.044439
validation RMSE: 0.062361
validation R2: 0.996181
lr: 3e-05
elapsed: 1479.1s
GPU allocated: 4.99 GiB
Epoch 6/10 | step 3000 | train loss 0.015225 | lr 3e-05 | elapsed 1519.6s | GPU memory 4.99 GiB
Depth 10 | Epoch 6/10
train loss: 0.014717
validation MAE_norm: 0.036624
validation RMSE: 0.051366
validation R2: 0.997409
lr: 3e-05
elapsed: 1791.4s
GPU allocated: 4.99 GiB
Epoch 7/10 | step 4000 | train loss 0.013617 | lr 3e-05 | elapsed 2025.6s | GPU memory 4.99 GiB
Depth 10 | Epoch 7/10
train loss: 0.013392
validation MAE_norm: 0.029915
validation RMSE: 0.042031
validation R2: 0.998265
lr: 3e-05
elapsed: 2085.8s
GPU allocated: 4.99 GiB
Depth 10 | Epoch 8/10
train loss: 0.010979
validation MAE_norm: 0.027194
validation RMSE: 0.038312
validation R2: 0.998558
lr: 3e-05
elapsed: 2387.0s
GPU allocated: 4.99 GiB
Epoch 9/10 | step 5000 | train loss 0.010354 | lr 3e-05 | elapsed 2542.1s | GPU memory 4.99 GiB
Depth 10 | Epoch 9/10
train loss: 0.010012
validation MAE_norm: 0.029848
validation RMSE: 0.039356
validation R2: 0.998479
lr: 3e-05
elapsed: 2682.2s
GPU allocated: 4.99 GiB
Depth 10 | Epoch 10/10
train loss: 0.008478
validation MAE_norm: 0.024326
validation RMSE: 0.032505
validation R2: 0.998962
lr: 3e-05
elapsed: 2993.8s
GPU allocated: 4.99 GiB
PASS — Depth 10 complete; validation MAE_norm=0.024326031814714984
Checkpoint saved: <REPOSITORY_ROOT>/experiments/xlstm_depth_v1/depth_10/best_checkpoint.pt

# P. Validation comparison

In [21]:
from src.mepi_v1.xlstm_depth import summarize_depth_experiment
comparison = summarize_depth_experiment(PROJECT_ROOT)
comparison_df = pd.DataFrame(comparison).rename(columns={'training_runtime_seconds': 'runtime', 'best_checkpoint_sha256': 'checkpoint_sha256'})
display_columns = ['depth','parameter_count','best_epoch','validation_mae_norm','validation_rmse','validation_r2','runtime','peak_gpu_memory_gib','checkpoint_sha256','training_horizon_boundary_reached']
completed_df = comparison_df[comparison_df['status'] == 'COMPLETE'][display_columns].sort_values('validation_mae_norm')
print('PASS — comparison uses validation metrics only and is sorted by validation MAE_norm')
completed_df

PASS — comparison uses validation metrics only and is sorted by validation MAE_norm

,depth,parameter_count,best_epoch,validation_mae_norm,validation_rmse,validation_r2,runtime,peak_gpu_memory_gib,checkpoint_sha256,training_horizon_boundary_reached
0,8,5969930,10,0.020495,0.027949,0.999233,2381.536420,4.153300,fdbeb87932dd6e20c45104f2ff074e267b414587a5ce9e...,True
1,10,7286794,10,0.024326,0.032505,0.998962,2993.800992,4.985282,3f78fba42614bf06c0cd8b36982b183cbd581710fa6034...,True
2,4,3336202,9,0.026314,0.037244,0.998638,1389.462312,2.485726,0570fc6a0feca68fa7bfb67edd1082b97f77411bb12ed8...,False
3,6,4653066,10,0.028504,0.037054,0.998652,1869.379593,3.319738,1b960ee46dc6cf676bfe70894c10b07bb04ab2d3e40f83...,True
4,2,2019338,9,0.034605,0.049907,0.997554,978.738730,1.654724,3b7795b2f9f09b1c0a6d1eab1603fe30892f62c8742d03...,False

# Q. Selected depth

In [22]:
if len(completed_df) == len(DEPTHS):
    selected_depth = int(completed_df.iloc[0]['depth'])
    print(f'SELECTED xLSTM DEPTH = {selected_depth}')
    print('SELECTION CRITERION =\nminimum validation MAE_norm')
    print('TEST DATA ACCESSED =\nNO')
else:
    selected_depth = None
    print(f'PENDING — {len(completed_df)}/{len(DEPTHS)} candidates are complete; no depth selected')

SELECTED xLSTM DEPTH = 8
SELECTION CRITERION =
minimum validation MAE_norm
TEST DATA ACCESSED =
NO

# R. Reproducibility and evidence summary

In [23]:
print('PASS — reproducibility/evidence summary')
print(f'Official pretraining tree SHA-256: {official_before["tree_sha256"]}')
print(f'Dataset SHA-256: {EXPECTED_DATASET_SHA256}')
print(f'Train manifest SHA-256: {EXPECTED_TRAIN_SHA256}')
print(f'Validation manifest SHA-256: {EXPECTED_VALIDATION_SHA256}')
print('Test manifest/dataset access: NO')
print('A best_epoch equal to 10 is reported as TRAINING_HORIZON_BOUNDARY_REACHED=True; no run is extended.')
completed_df

PASS — reproducibility/evidence summary
Official pretraining tree SHA-256: c88efbb07c7d18042e71cc87b3b63c5d0c02d6d7600c34368b35755ab3129265
Dataset SHA-256: 0aca43184e9bd6cc90eec736a89fe1ea32f45b126527cb97918cd92684ac2c19
Train manifest SHA-256: 2e06050bbe1cff8b6f4f7ae3a99788d6914e214353a5e6a2f2ece7463b6377b0
Validation manifest SHA-256: aa7d1ee30ca3f3967eadee81d2a31e0a9bcb7e0bc5421f36cb849d6da1dc9749
Test manifest/dataset access: NO
A best_epoch equal to 10 is reported as TRAINING_HORIZON_BOUNDARY_REACHED=True; no run is extended.

,depth,parameter_count,best_epoch,validation_mae_norm,validation_rmse,validation_r2,runtime,peak_gpu_memory_gib,checkpoint_sha256,training_horizon_boundary_reached
0,8,5969930,10,0.020495,0.027949,0.999233,2381.536420,4.153300,fdbeb87932dd6e20c45104f2ff074e267b414587a5ce9e...,True
1,10,7286794,10,0.024326,0.032505,0.998962,2993.800992,4.985282,3f78fba42614bf06c0cd8b36982b183cbd581710fa6034...,True
2,4,3336202,9,0.026314,0.037244,0.998638,1389.462312,2.485726,0570fc6a0feca68fa7bfb67edd1082b97f77411bb12ed8...,False
3,6,4653066,10,0.028504,0.037054,0.998652,1869.379593,3.319738,1b960ee46dc6cf676bfe70894c10b07bb04ab2d3e40f83...,True
4,2,2019338,9,0.034605,0.049907,0.997554,978.738730,1.654724,3b7795b2f9f09b1c0a6d1eab1603fe30892f62c8742d03...,False

# S. Downstream status

In [24]:
if selected_depth is not None:
    print('MAGNET DEPTH STUDY: COMPLETE')
else:
    print('MAGNET DEPTH STUDY: INCOMPLETE')
print('DOWNSTREAM DEPTH CONFIRMATION:')
print('WAITING FOR REAL FINETUNE DATA')
print('No downstream fine-tuning, loss-weight, final-test, or frequency-screening result was generated here.')

MAGNET DEPTH STUDY: COMPLETE
DOWNSTREAM DEPTH CONFIRMATION:
WAITING FOR REAL FINETUNE DATA
No downstream fine-tuning, loss-weight, final-test, or frequency-screening result was generated here.